#:schema node_modules/wrangler/config-schema.json
name = "linux-isos-scraping"
main = "src/index.js"
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]

routes = [
	{ pattern = "linuxisos.gmem.ca", custom_domain = true }
]

[assets]
directory = "./static"
binding = "ASSETS"
run_worker_first = true

[triggers]
crons = ["0 0 * * *"]

[[r2_buckets]]
binding = "R2"
bucket_name = "linuxtorrents"
preview_bucket_name = "linuxtorrents"

[[workflows]]
name = "debian-workflow"
binding = "DEBIAN_WORKFLOW"
class_name = "DebianWorkflow"

[[workflows]]
name = "archlinux-workflow"
binding = "ARCHLINUX_WORKFLOW"
class_name = "ArchLinuxWorkflow"

[observability]
enabled = true
